---
# Workflow list definition
workflow:
  - second_job

# Shared definition block
shared:
  # Source: https://hub.docker.com/r/library/buildpack-deps/
  image: hello-world

# Job definition block
# "main" is a default job that all pipelines have
jobs:
  main:
    # Steps definition block.
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
  second_job:
    steps:
      - run_arbitrary_script: ./my_script.sh
